
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { Navbar } from "./_componant/Navbar";
import Myprovder from "./_provider/Myprovder";
import "./globals.css";
import CartContextProvider from "./_context/CartContextProvider";
import { getUserCart } from "./_action/cart.action";
import { getAllWishlist } from "./_action/wishlist.action";
import { WishContextProvider } from "./_context/WishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const userCart = await getUserCart()
  const Wishlist = await getAllWishlist()


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SessionProvider> */}
        
          <Myprovder>

            <CartContextProvider  userCart={userCart}>
              <WishContextProvider Wishlist={Wishlist} >

        <Navbar/>
                
         <Toaster />

          {children}

              </WishContextProvider>
            </CartContextProvider>

          </Myprovder>
          {/* </SessionProvider>  */}
      </body>
    </html>
  );
}
